# directories containing preprocessed data
data :
  tiff : data/tiff
  numpy : data/numpy
  png : data/png
# login to radar database
login:
  username : flippert
  password : eFd5cqJqpv8hJN2D
# start time
ts : 2016-10-01 00:00:00
# end time
te : 2016-10-01 02:00:00
# time resolution in minutes
tr : 15
# list of radar stations
radars :
  - NL/DBL
  - NL/DHL
  - NL/HRW
  - BE/JAB
  - BE/ZAV
# radar quantity
quantity : VID
# raster resolution
res : 0.01
# max reach of radars (added to bbox dimensions)
reach : 5
