# directories containing preprocessed data
data :
  vid : /home/flipper/radar_data/vid/HRW_res=0.01_filtered
  vpi : /home/fiona/radar_data/vpi/test
# login to radar database
login:
  username : flippert
  password : eFd5cqJqpv8hJN2D
# start time
ts : 2018-09-01 00:00:00
# end time
te : 2018-09-03 00:00:00
# time resolution in minutes
tr : 5
#tr : 15
# list of radar stations
radars :
#  - NL/DBL
  - NL/DHL
  - NL/HRW
  - BE/JAB
#  - BE/ZAV
#  - DE/BOO
# radar quantity for 2D vertical integration
quantity : VID
# raster resolution for 2D vertical integration
res : 0.01
#res : 0.1
# max reach of radars (added to bbox dimensions)
reach : 5
#reach : 3
# rain filter
filter :
  DR_min : -12
  DBZ_max : 35
#  DR_min : NaN
#  DBZ_max : NaN
