# directories containing preprocessed data
data :
  ppi : data/ppi/NL/HRW_res=0.1
# login to radar database
login:
  username : flippert
  password : eFd5cqJqpv8hJN2D
# start time
ts : 2018-08-01 00:00:00
# end time
te : 2018-11-15 23:45:00
# time resolution in minutes
tr : 15
# list of radar stations
radars :
#  - NL/DBL
#  - NL/DHL
  - NL/HRW
#  - BE/JAB
#  - BE/ZAV
# radar quantity
quantity : VID
# raster resolution
#res : 0.01
res : 0.1
# max reach of radars (added to bbox dimensions)
#reach : 5
reach : 5
