# main config file
experiment: grid_search
defaults:
  - datasource: radar
  - action: training
  - model: LocalLSTM
root: /home/fiona/birdMigration
season: fall
seed: 1234
repeats: 1
cuda: True
root_transform: 0
missing_data_threshold: 0.1
t_unit: 1H
edge_type: voronoi
birds_per_km2: false
max_distance: 0
n_dummy_radars: 0
use_nights: true
data_perc: 1.0
exclude: []
