# main config file
experiment: grid_search
defaults:
  - datasource: radar
  - action: training
  - model: GBT
settings:
  root: /home/fiona/birdMigration
  season: fall
  seed: 1234
  repeats: 5
  cuda: False
