# main config file
output_dir: results
action: ???
defaults:
  - datasource: radar
  - model: BirdFluxGraphLSTM
  - device: cluster
  - hp_search_space: ${model.name}
job_id: 0
season: fall
seed: 1234
model_seed: ${seed}
root_transform: 0
missing_data_threshold: 0.1
t_unit: 1H
use_nights: false
data_perc: 0.2
exclude: []
verbose: True
debugging: False
