# main config file
experiment: grid_search
defaults:
  - datasource: radar
  - action: training
  - model: GBT
root: /home/fiona/birdMigration
season: fall
seed: 1234
repeats: 5
cuda: False
root_transform: 0
missing_data_threshold: 0.1
t_unit: 1H
edge_type: voronoi
max_distance: 0
n_dummy_radars: 15