# main config file
experiment: test
job_id: 0
action: cv
defaults:
  - datasource: radar
  - model: BirdFluxGraphLSTM
  - hp_search_space: NNs
cv_settings:
  - n_folds=5
  - repeats=1
root: /home/flippert/birdMigration
output_dir: results
season: fall
seed: 1234
cuda: True
root_transform: 0
missing_data_threshold: 0.1
t_unit: 1H
use_nights: true
data_perc: 1.0
exclude: []
