# main config file
experiment: test
root: /home/flippert/birdMigration
output_dir: results
job_id: 0
action: training+testing
defaults:
  - datasource: radar
  - model: BirdFluxGraphLSTM
  - hp_search_space: LR
season: fall
seed: 1234
model_seed: ${seed}
cuda: True
root_transform: 0
missing_data_threshold: 0.1
t_unit: 1H
use_nights: true
data_perc: 1.0
exclude: []
