# main config file
experiment: test
job_id: 0
defaults:
  - datasource: radar
  - model: LocalLSTM
  - hp_search_space: NNs
root: /home/fiona/birdMigration
output_dir: results
season: fall
seed: 1234
repeats: 1
cuda: True
root_transform: 0
missing_data_threshold: 0.1
t_unit: 1H
edge_type: voronoi
birds_per_km2: false
max_distance: 0
n_dummy_radars: 0
use_nights: true
data_perc: 1.0
exclude: []
