# start time
ts : 2015-08-01 00:00:00
# end time
te : 2015-11-30 23:59:59
# time resolution in minutes
tr : 5
# list of radar stations
radars :
  - NL/DBL
  - NL/DHL
  - NL/HRW
  - BE/JAB
  - BE/WID
  - BE/ZAV
  - DE/ASB
  - DE/BOO
  - DE/DRS
  - DE/EIS
  - DE/EMD
  - DE/ESS
  - DE/FBG
  - DE/FLD
  - DE/HNR
  - DE/ISN
  - DE/MEM
  - DE/NEU
  - DE/NHB
  - DE/OFT
  - DE/PRO
  - DE/ROS
  - DE/TUR
  - DE/UMD
night_only : false
regularize: false
alt_min : 200
alt_max : 5000

# radar quantity for 2D vertical integration
#quantity : VID
# raster resolution for 2D vertical integration
#res : 0.01
#res : 0.1
# max reach of radars (added to bbox dimensions)
#reach : 5
#reach : 3
# rain filter
#filter :
#  DR_min : -12
#  DBZ_max : 35
#  DR_min : NaN
#  DBZ_max : NaN
