# start time
ts : 2019-08-01 00:00:00
# end time
#te : 2019-11-30 23:59:59
te : 2019-08-05 23:59:59
# list of radar stations
radars :
  - KILN # Ohio
  - KCLE # Ohio
  - KVWX # Indiana
  - KIND # Indiana
  - KIWX # Indiana
  - KJKL # Kentucky
  - KLVX # Kentucky
  - KPAH # Kentucky
  - KHPX # Kentucky
night_only : false
regularize: false
alt_min : 200
alt_max : 5000

