name: birdmigration
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.8.3
  - pip
  - numpy
  - tqdm
  - yaml
  - geopy
  - geopandas
  - xarray
  - networkx
  - rioxarray
  - wradlib
  - rasterio
  - cartopy
  - cdsapi
  - pvlib
  - hydra-core>=1.3.2
