name: birdmigration
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.8.3
  - numpy
  - tqdm
  - yaml
  - geopy
  - shapely
  - pandas
  - geopandas
  - matplotlib
  - xarray
  - networkx
  - rioxarray
  - pyproj
  - geopy
  - wradlib
  - scikit-learn
  - rasterio
  - pillow
  - cartopy
  - imageio
  - pip:
  	- cdsapi==0.5.1
    	- geovoronoi==0.3.0
    	- pvlib==0.8.1
