name: birdmigration
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.8.3
  - pip
  - numpy
  - tqdm
  - yaml
  - geopy
  #- shapely
  #- pandas
  - geopandas
  #- matplotlib
  - xarray
  - networkx
  - rioxarray
  #- pyproj
  - wradlib
  #- scikit-learn
  - rasterio
  - cartopy
  - cdsapi
  - pvlib
  - hydra-core>=1.3.2
  #- pip:
    #- geovoronoi==0.4.0
    #- pvlib==0.8.1
