experiment: boundary_lstm_encoder_no_nights
root: /scratch
season: fall
seed: 1234
repeats: 5
cuda: true
root_transform: 0
missing_data_threshold: 0.1
t_unit: 1H
edge_type: voronoi
birds_per_km2: false
max_distance: 0
n_dummy_radars: 0
use_nights: false
data_perc: 1.0
exclude: []
datasource:
  name: radar
  training_years:
  - 2016
  - 2017
  validation_year: 2015
  test_year: 2015
  val_test_split: 0.25
  env_vars:
  - u
  - v
  - cc
  - tp
  - sp
  - t2m
  - sshf
  use_buffers: true
  bird_scale: 9938497.9440479
action:
  name: training
  grid_search: false
model:
  name: BirdFluxGraphLSTM
  hyperparameters:
    n_hidden:
      default: 64
      search_space:
      - 64
      - 128
    n_fc_layers:
      default: 2
      search_space:
      - 1
      - 2
    n_fc_layers_fluxmlp:
      default: 2
      search_space:
      - 1
      - 2
    n_hidden_fluxmlp:
      default: 64
      search_space:
      - 64
      - 128
    n_lstm_layers:
      default: 1
      search_space:
      - 1
    dropout_p:
      default: 0.25
      search_space:
      - 0.25
    lr:
      default: 0.0001
      search_space:
      - 0.001
      - 0.0001
      - 1.0e-05
    lr_decay:
      default: 100
      search_space:
      - 50
    teacher_forcing_gamma:
      default: 0.95
      search_space:
      - 0.9
    conservation_constraint:
      default: 0.0
      search_space:
      - 0.0
      - 0.01
      - 0.1
  epochs: 200
  horizon: 40
  fixed_boundary: true
  force_zeros: false
  use_encoder: true
  context: 24
  root_transformed_loss: false
  enforce_conservation: false
  compute_fluxes: true
  boundary_constraint_only: true
  perturbation_std: 0
  perturbation_mean: 0
  batch_size: 1
  boundary_model: LocalLSTM
  load_states_from: none
