# settings for ABM simulation
year: '2015'
season: fall
start_date: 08-01 12:00
end_date: 09-15 12:00
num_birds: 5000

settings:
  start_day_mean: 15
  start_day_std: 5
  energy_tol_mean: 1.0
  energy_tol_std: 0.1
  compensation: 0.75