# settings for ABM simulation
year: '2017'
season: fall
start_date: 09-01 12:00
end_date: 09-05 12:00
num_birds: 100

settings:
  energy_tol_mean: 1.0
  energy_tol_std: 0.1
  compensation: 0.75
  start_day_range: 5
  departure_window: 3
#  start_day_mean: 15
#  start_day_std: 5
#  sources:
#    - [9.58, 54.50] # Schleswig-Holstein
#    - [11.91, 54.10] # Rostock
#    - [13.79, 54.83] # Meck-Pom
#    - [15.13, 52.42] # Poland
#  source_std: 0.5
