experiment: fixed_boundary_encoder_nights_2
root: /scratch
output_dir: /home/flippert/birdMigration/checkpoints/birdflux_array_job_7751863
season: fall
seed: 7751863
repeats: 1
cuda: true
root_transform: 0
missing_data_threshold: 0.1
t_unit: 1H
edge_type: voronoi
birds_per_km2: false
max_distance: 0
n_dummy_radars: 0
use_nights: true
data_perc: 0.1
exclude: []
datasource:
  name: radar
  training_years:
  - 2016
  - 2017
  validation_year: 2015
  test_year: 2015
  val_test_split: 0.25
  val_train_split: 0.1
  env_vars:
  - u
  - v
  - cc
  - tp
  - sp
  - t2m
  - sshf
  use_buffers: true
  bird_scale: 9938497.9440479
action:
  name: training
  grid_search: true
model:
  name: BirdFluxGraphLSTM
  n_hidden: 64
  n_fc_layers: 2
  n_fc_layers_fluxmlp: 2
  n_hidden_fluxmlp: 64
  n_lstm_layers: 1
  dropout_p: 0.25
  lr: 0.0001
  lr_decay: 50
  teacher_forcing_gamma: 0.95
  conservation_constraint: 0.0
  epochs: 2
  horizon: 40
  fixed_boundary: true
  force_zeros: false
  use_encoder: true
  context: 24
  root_transformed_loss: false
  enforce_conservation: false
  compute_fluxes: true
  boundary_constraint_only: true
  perturbation_std: 0
  perturbation_mean: 0
  batch_size: 1
  boundary_model: none
  load_states_from: none
