# path to preprocessed data
datadir : data
# login to radar database
username : flippert
password : eFd5cqJqpv8hJN2D
# start time
ts : 2016-10-1 00:00
# end time
te : 2016-10-1 04:00
# time resolution in minutes
tr : 15
# list of radar stations
radars :
  - NL/DBL
  - NL/DHL
  - NL/HRW
  - BE/JAB
  - BE/ZAV
# radar quantity
quantity : VID
#
res : 0.01
