# @package _group_
name: BirdFluxGraphLSTM
n_hidden: 128
n_fc_layers: 2
n_lstm_layers: 1
dropout_p: 0.25
lr: 0.00005
lr_decay: 200
lr_gamma: 0.1
teacher_forcing_gamma: 0.95
flux_loss_weight: 0.0
epochs: 200
horizon: 40
test_horizon: 64
fixed_boundary: false
force_zeros: false
use_encoder: true
use_boundary_model: true
context: 24
root_transformed_loss: false
compute_fluxes: true
batch_size: 8
boundary_model: Extrapolation
load_states_from: none
edge_type: voronoi
birds_per_km2: false
n_dummy_radars: 15
