# @package _group_
name: BirdFluxGraphLSTM
n_hidden: 128
n_fc_layers: 2
#n_fc_layers_fluxmlp: 2
#n_hidden_fluxmlp: 64
n_lstm_layers: 1
dropout_p: 0.25
lr: 0.0001
lr_decay: 100
lr_gamma: 0.1
teacher_forcing_gamma: 0.95
conservation_constraint: 0.0
epochs: 200
horizon: 40
test_horizon: 64
fixed_boundary: false
force_zeros: false
use_encoder: false
use_boundary_model: true
context: 0
root_transformed_loss: false
#enforce_conservation: false
compute_fluxes: true
boundary_constraint_only: false
perturbation_std: 0
perturbation_mean: 0
batch_size: 1
boundary_model: Extrapolation
load_states_from: none
edge_type: voronoi
birds_per_km2: false
n_dummy_radars: 15
