# @package _group_
name: LocalMLP
n_hidden: 128
n_layers: 2
dropout_p: 0.25
lr: 0.0001
lr_decay: 100
epochs: 200
horizon: 24
test_horizon: 64
force_zeros: false
use_acc_vars: true
root_transformed_loss: false
batch_size: 1
edge_type: none
birds_per_km2: true
n_dummy_radars: 0
